2022-08-17 00:07:16,834 (357c) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 87136b9 (Tue Aug 16 04:39:41 UTC 2022)
2022-08-17 00:07:16,834 (357c) :  DEBUG (core:361) - Using the elevated policy
2022-08-17 00:07:16,834 (357c) :  DEBUG (core:450) - Starting runtime component.
2022-08-17 00:07:16,835 (357c) :  DEBUG (core:450) - Starting caching component.
2022-08-17 00:07:16,836 (357c) :  DEBUG (core:450) - Starting data component.
2022-08-17 00:07:16,836 (357c) :  DEBUG (core:450) - Starting networking component.
2022-08-17 00:07:16,836 (357c) :  DEBUG (networking:265) - No cookie jar found
2022-08-17 00:07:16,838 (357c) :  DEBUG (networking:428) - Setting the default network timeout to 20.0
2022-08-17 00:07:16,839 (357c) :  DEBUG (core:450) - Starting localization component.
2022-08-17 00:07:16,839 (357c) :  INFO (localization:409) - Setting the default locale to en-us
2022-08-17 00:07:16,839 (357c) :  DEBUG (core:450) - Starting messaging component.
2022-08-17 00:07:16,841 (357c) :  DEBUG (core:450) - Starting debugging component.
2022-08-17 00:07:16,841 (357c) :  DEBUG (core:450) - Starting services component.
2022-08-17 00:07:16,842 (357c) :  DEBUG (core:450) - Starting myplex component.
2022-08-17 00:07:16,842 (1da4) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.agents.thetvdb'
2022-08-17 00:07:16,842 (357c) :  DEBUG (core:450) - Starting notifications component.
2022-08-17 00:07:16,917 (357c) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.agents.thetvdb in namespace 'metadata'
2022-08-17 00:07:16,920 (357c) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2022-08-17 00:07:16,943 (357c) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2022-08-17 00:07:16,944 (357c) :  CRITICAL (core:574) - Exception getting hosted resource hashes (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-87136b92b\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-87136b92b\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 242, in content
    return self.__str__()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-87136b92b\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 220, in __str__
    self.load()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-87136b92b\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 158, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2022-08-17 00:07:16,950 (778) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2022-08-17 00:07:16,950 (357c) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2022-08-17 00:07:16,951 (357c) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2022-08-17 00:07:16,951 (778) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2022-08-17 00:07:16,953 (2e48) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400'
2022-08-17 00:07:16,953 (357c) :  DEBUG (core:150) - Finished starting framework core
2022-08-17 00:07:16,953 (357c) :  DEBUG (core:560) - Loading plug-in code
2022-08-17 00:07:16,956 (2e48) :  DEBUG (core:538) - Machine identifier is 1fdbb643d7ecf4de09d917684ebc0c17c09d7032
2022-08-17 00:07:16,956 (2e48) :  DEBUG (core:539) - Server version is 1.28.1.6092-87136b92b
2022-08-17 00:07:16,959 (778) :  DEBUG (services:362) - Loaded services
2022-08-17 00:07:16,982 (1c0c) :  DEBUG (services:438) - No shared code to load
2022-08-17 00:07:17,176 (357c) :  DEBUG (core:566) - Finished loading plug-in code
2022-08-17 00:07:17,177 (357c) :  DEBUG (agentkit:1132) - Creating new agent class called TVDBAgent
2022-08-17 00:07:17,177 (357c) :  DEBUG (agentkit:937) - Updating agent information: [{'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'languages': ['en', 'fr', 'zh', 'sv', 'no', 'da', 'fi', 'nl', 'de', 'it', 'es', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'cs', 'ko', 'sl', 'hr'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'TheTVDB'}]
2022-08-17 00:07:17,178 (357c) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo1CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdAoyCnMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudG5zMTQKY29udHJpYnV0ZXNfdG9yNApzOQpsYW5ndWFnZXNiMXMyMApwZXJzaXN0X3N0b3JlZF9maWxlc2kwCnM3CnZlcnNpb25iMXMxNgpwcmltYXJ5X3Byb3ZpZGVyYjFzNQpwcmVmc3M3ClRoZVRWREJzNApuYW1lMQpzNwpUVl9TaG93MjMKczIKZW5zMgpmcnMyCnpoczIKc3ZzMgpub3MyCmRhczIKZmlzMgpubHMyCmRlczIKaXRzMgplc3MyCnBsczIKaHVzMgplbHMyCnRyczIKcnVzMgpoZXMyCmphczIKcHRzMgpjc3MyCmtvczIKc2xzMgpocnIwCg__'
2022-08-17 00:07:36,148 (357c) :  INFO (core:611) - Started plug-in
2022-08-17 00:07:36,148 (357c) :  DEBUG (socketinterface:160) - Starting socket server
2022-08-17 00:07:36,148 (357c) :  DEBUG (runtime:1117) - Created a thread named 'start'
2022-08-17 00:07:36,148 (357c) :  INFO (socketinterface:184) - Socket server started on port 50913
2022-08-17 00:07:36,148 (357c) :  INFO (pipeinterface:25) - Entering run loop
2022-08-17 00:07:36,148 (357c) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2022-08-17 00:07:36,148 (357c) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2022-08-17 00:07:36,148 (357c) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 151 bytes
2022-08-17 00:07:36,187 (31d4) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2022-08-17 00:07:36,187 (31d4) :  CRITICAL (core:574) - Exception matching route for path "/" (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-87136b92b\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2022-08-17 00:07:36,196 (31d4) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2022-08-17 00:07:36,196 (31d4) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2022-08-17 00:07:36,196 (31d4) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
